using DevExpress.XtraEditors;
using PMWORK.Repository;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace PMWORK.SensorForm
{
    public partial class MachineryCounterDeviceForm : XtraForm
    {
        private readonly ISensorRepository _sensorRepository;

        public MachineryCounterDeviceForm(ISensorRepository sensorRepository)
        {
            InitializeComponent();
            _sensorRepository = sensorRepository;


            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            PMWORK.AppDbContext dbContext = new PMWORK.AppDbContext();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.MachineryCounterDevices.Load();
            // This line of code is generated by Data Source Configuration Wizard
            machineryCounterDevicesBindingSource.DataSource = dbContext.MachineryCounterDevices.Local.ToBindingList();
        }
    }
}
