// <auto-generated />
namespace PMWORK.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class D2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(D2));
        
        string IMigrationMetadata.Id
        {
            get { return "202107051848354_D2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
